# Generated by Django 4.2.27 on 2026-02-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
