# Generated by Django 4.2.27 on 2026-02-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='emergency_phone',
            new_name='emergency_contact',
        ),
    ]
