# Generated by Django 4.2.27 on 2026-02-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_emergency_contact_and_more'),
        ('tracking', '0002_buslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='accounts.driverprofile'),
        ),
    ]
